name: asl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pandas
  - pillow
  - jupyter
  - ipykernel
  - opencv
  - fonttools
  - pyyaml
  - tqdm
  - seaborn

  - pip:
      - mediapipe
